FROM docker.elastic.co/elasticsearch/elasticsearch:7.5.1

ADD docker/elasticsearch/jvm.options /usr/share/elasticsearch/config/
ADD docker/elasticsearch/elasticsearch.yml /usr/share/elasticsearch/config/

EXPOSE 9200
