# ./docker-compose.yml

version: '3'

services:
  elasticsearch:
    container_name: elasticsearch    
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    build:
        context: ../..
        dockerfile: docker/elasticsearch/Dockerfile 
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
        - "9200:9200"
    volumes:
        - "C:/elastic/elasticsearch-7.7.0/data:/var/lib/elasticsearch/data"
        - "C:/elastic/elasticsearch-7.7.0/logs:/var/log/elasticsearch"
    networks:
        - docker-network

  kibana:
    container_name: kibana   
    image: docker.elastic.co/kibana/kibana:7.5.1
    build:
        context: ../..
        dockerfile: docker/kibana/Dockerfile  
    depends_on:
        - elasticsearch
    environment:
        SERVER_HOST: 0.0.0.0
        ELASTICSEARCH_URL: http://elasticsearch:9200        
    ports:
      - "5601:5601"
    networks:
        - docker-network

networks:
    docker-network:
        driver: bridge